# Site settings
title:       Kyle Sun's Blog
email:       skx926@gmail.com 
author:      Kyle Sun
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         ""

#Duoshuo short Name / 多说的shortname
duoshuo: skx926

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze: eb644977e4ba55deb38e461b9bf84176 

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: skx926
twitter_username: kes0n
weibo_username: ikeson
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     10
sass:
compressed: true
